// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Relay;

public class CompressorSS extends SubsystemBase {
    
    private Compressor compressor;
    private Relay relay;

    public CompressorSS() {
        compressor = new Compressor(Constants.kPCM_CANID);
        relay = new Relay(Constants.kCompressorRelay);
    }

    // public void turnOnCompressor() {
    //     System.out.println("Starting compressor");
    //     compressor.start();
    //     relay.set(Value.kForward);
    // }

    // public void turnOffCompressor() {
    //     relay.set(Value.kOff);
    // }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        compressor.start();
        //Add an if/else statement. use the pressure switch,
        // which is under the compressor object as the argument,
        // i.e. the true false factor.
        // if true set the Relay to kForward else kOff
        if (compressor.getPressureSwitchValue() == false) {
            relay.set(Relay.Value.kForward);
            System.out.println("Turning compressor on");
        }
        else {
            relay.set(Relay.Value.kOff);
            System.out.println("Turning compressor off");
        }

    }

    
}

