// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import edu.wpi.first.wpilibj.DoubleSolenoid;

/**
 *
 */
public class intakeArm extends SubsystemBase {

    private DoubleSolenoid rightPiston;
    private DoubleSolenoid leftPiston;

    public intakeArm() {
       
        rightPiston = new DoubleSolenoid(Constants.kPCM_CANID, Constants.kArmSolenoidRightForwardChannel,
            Constants.kArmSolenoidRightReverseChannel);
        
        leftPiston = new DoubleSolenoid(Constants.kPCM_CANID, Constants.kArmSolenoidLeftForwardChannel,
            Constants.kArmSolenoidLeftReverseChannel);
    }

    public boolean armLowered = false;
    public void lowerArm() {
        leftPiston.set(DoubleSolenoid.Value.kForward);
        rightPiston.set(DoubleSolenoid.Value.kForward);
        armLowered = true;
    }
    public void raiseArm() {
        leftPiston.set(DoubleSolenoid.Value.kReverse);
        rightPiston.set(DoubleSolenoid.Value.kReverse);
        armLowered = false;
    }
   
}

