// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class IntakeArm extends SubsystemBase {

    private DoubleSolenoid m_piston;

    public IntakeArm() {
       
        m_piston = new DoubleSolenoid(Constants.kPCM_CANID, Constants.kArmSolenoidForwardChannel,
            Constants.kArmSolenoidReverseChannel);
    }

    public boolean armLowered = false;
    public void lowerArm() {
        SmartDashboard.putString("IntakeArm", "Forward (down)");
        System.out.println("Setting IntakeArm Forward (down)");
        m_piston.set(DoubleSolenoid.Value.kForward);
        armLowered = true;
    }
    public void raiseArm() {
        SmartDashboard.putString("IntakeArm", "Reverse (up)");
        System.out.println("Setting IntakeArm Reverse (up)");
        m_piston.set(DoubleSolenoid.Value.kReverse);
        armLowered = false;
    }
   
}

